# Menu items are updated each day at 4:44 UTC.
name: Update Food

on:
  push:
    branches:
      main

jobs:
  scrape:
    runs-on: ubuntu-latest
    name: Web Scrape
    steps:
    # Clones repository
    - uses: actions/checkout@v4
    # Sets up Python
    - uses: actions/setup-python@v5 
      with:
        python-version: '3.12.1'
    # Installs requirements
    - run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
    - run: |
        cd src
        python scrape.py
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}